[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "openai>=1.63.2",
    "pydantic>=2.10.6",
    "streamlit>=1.42.2",
    "trafilatura>=2.0.0",
    "uvicorn>=0.34.0",
]
